# These will be overridden by the publish workflow and set to the new tag
name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Optionally configure your categories and other templates
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '📖 Documentation'
    label: 'documentation'

change-template: '- $TITLE @$AUTHOR ([#${NUMBER}]($URL))'
change-title-escapes: 'false' # Disable all escaping to allow full markdown in titles

template: |
  ## 📝 Changes

  $CHANGES
  
  ---
  🏷 **Version**: `v$RESOLVED_VERSION` 