import { ModuleStatus } from './structure.interface';

export enum ComRequestType {
    DIGITAL_INPUT = 'DIGITAL_INPUT',
    DIGITAL_OUTPUT = 'DIGITAL_OUTPUT',
    ANALOG_OUTPUT = 'ANALOG_OUTPUT',
    ANALOG_INPUT = 'ANALOG_INPUT',
    INVERTER_INIT = 'INVERTER_INIT',
    INVERTER_RESET = 'INVERTER_RESET',
    INVERTER_WRITE = 'INVERTER_WRITE',
    INVERTER_READ = 'INVERTER_READ',
}
